package forgeweb.fs;

import org.teavm.runtime.fs.VirtualFile;
import org.teavm.runtime.fs.VirtualFileSystem;
import org.teavm.runtime.fs.VirtualFileSystemProvider;

import java.io.IOException;

/**
 * The java.io file system for the web build.
 *
 * Game data is described by a manifest ("path\tsize[\turl]" per line, generated by
 * scripts/build-webdata) and mounted read-through. Listings and sizes come from the
 * manifest, and contents are downloaded on first read. Everything written at runtime
 * (preferences, saves, caches) lives in memory, and {@link UserDataStore} persists it.
 */
public final class WebFileSystem extends FileStore implements VirtualFileSystem {
    /** Downloaded card pictures kept in memory: about 640 at 100 KB each (measured). A picture dropped from here is not
     *  downloaded again until its list item is created again, so this is a ceiling for very long sessions. */
    static final long PICTURE_CACHE_BYTES = 64L << 20;

    private String userDir = "/";

    private WebFileSystem() {
        super(new BrowserHost());
    }

    /** Mounts the manifest at {@code mountPoint} and installs this as TeaVM's file system. */
    public static WebFileSystem install(String mountPoint, String manifestUrl, String baseUrl) throws IOException {
        WebFileSystem fs = new WebFileSystem();
        fs.mountManifest(mountPoint, Http.getText(manifestUrl), baseUrl);
        UserDataStore.setUserRoot(mountPoint + "data/");
        UserDataStore.restore(fs);
        fs.capFolder(mountPoint + "cache/pics/", PICTURE_CACHE_BYTES);
        fs.userDir = mountPoint;
        // For code that builds paths from user.dir (null on TeaVM otherwise).
        System.setProperty("user.dir", mountPoint);
        VirtualFileSystemProvider.setInstance(fs);
        return fs;
    }

    /** Downloads with XHR and times with setTimeout. */
    private static final class BrowserHost implements Host {
        @Override
        public byte[] fetch(String url) throws IOException {
            return Http.getBytes(url);
        }

        @Override
        public long now() {
            return System.currentTimeMillis();
        }

        @Override
        public void schedule(Runnable task, long delayMs) {
            setTimeout(task::run, (int) delayMs);
        }

        @Override
        public void recordFetch(String path) {
            WebFileSystem.recordFetch(path);
        }
    }

    @org.teavm.jso.JSFunctor
    interface Callback extends org.teavm.jso.JSObject {
        void call();
    }

    @org.teavm.jso.JSBody(params = {"callback", "ms"}, script = "setTimeout(callback, ms);")
    private static native void setTimeout(Callback callback, int ms);

    /** Game files read so far, packed or not (window.forgeFetched): scripts/record-startup
     *  turns those of a new game into the startup pack. */
    @org.teavm.jso.JSBody(params = "path", script = "(window.forgeFetched = window.forgeFetched || []).push(path);")
    private static native void recordFetch(String path);

    // --- VirtualFileSystem ---

    @Override
    public String getUserDir() {
        return userDir;
    }

    @Override
    public VirtualFile getFile(String path) {
        // java.io resolves relative paths before calling us; TeaVM's java.nio passes them raw.
        if (!path.startsWith("/")) {
            path = userDir + path;
        }
        return new WebVirtualFile(this, path);
    }

    @Override
    public boolean isWindows() {
        return false;
    }

    @Override
    public String canonicalize(String path) {
        return super.canonicalize(path);
    }

    @Override
    public String[] getRoots() {
        return new String[] {"/"};
    }
}
