package forgeweb.fs;

import org.teavm.runtime.fs.VirtualFile;
import org.teavm.runtime.fs.VirtualFileSystem;
import org.teavm.runtime.fs.VirtualFileSystemProvider;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The java.io file system for the web build.
 *
 * Game data is described by a manifest ("path\tsize[\turl]" per line, generated by
 * scripts/build-webdata) and mounted read-through. Listings and sizes come from the
 * manifest, and contents are downloaded on first read. Everything written at runtime
 * (preferences, saves, caches) lives in memory, and {@link UserDataStore} persists it.
 */
public final class WebFileSystem implements VirtualFileSystem {
    final Node root = new Node("", true);
    private String userDir = "/";
    /** Downloaded packs by URL (see scripts/build-webdata). Small, and read again and again. */
    private final Map<String, byte[]> packs = new HashMap<>();
    /** Remote files of at least {@link #BIG} bytes whose contents are in memory (see {@link #trim}). */
    private final java.util.List<Node> bigLoaded = new java.util.ArrayList<>();
    private long lastBigUse;
    private boolean trimScheduled;
    private int remoteFetches;
    private long remoteBytes;

    /** Mounts the manifest at {@code mountPoint} and installs this as TeaVM's file system. */
    public static WebFileSystem install(String mountPoint, String manifestUrl, String baseUrl) throws IOException {
        WebFileSystem fs = new WebFileSystem();
        fs.mountManifest(mountPoint, Http.getText(manifestUrl), baseUrl);
        UserDataStore.setUserRoot(mountPoint + "data/");
        UserDataStore.restore(fs);
        fs.userDir = mountPoint;
        // For code that builds paths from user.dir (null on TeaVM otherwise).
        System.setProperty("user.dir", mountPoint);
        VirtualFileSystemProvider.setInstance(fs);
        return fs;
    }

    private void mountManifest(String mountPoint, String manifest, String baseUrl) {
        Node mount = mkdirs(mountPoint);
        int files = 0;
        long total = 0;
        for (String line : manifest.split("\n")) {
            if (line.isEmpty() || line.startsWith("#")) continue;
            String[] cols = line.split("\t");
            String rel = cols[0];
            int size = Integer.parseInt(cols[1].trim());
            String url = cols.length > 2 ? cols[2].trim() : baseUrl + rel;
            int slash = rel.lastIndexOf('/');
            Node dir = slash < 0 ? mount : mkdirs(mount, rel.substring(0, slash));
            Node file = new Node(rel.substring(slash + 1), false);
            file.size = size;
            file.remoteUrl = url;
            if (cols.length > 3) file.packOffset = Integer.parseInt(cols[3].trim());
            file.readOnly = true;
            dir.addChild(file);
            files++;
            total += size;
        }
        System.out.println("[fs] mounted " + files + " files (" + (total / (1024 * 1024)) + " MB) at " + mountPoint);
    }

    // --- path handling ---

    static List<String> segments(String path) {
        List<String> out = new ArrayList<>();
        for (String s : path.split("/")) {
            if (s.isEmpty() || s.equals(".")) continue;
            if (s.equals("..")) {
                if (!out.isEmpty()) out.remove(out.size() - 1);
            } else {
                out.add(s);
            }
        }
        return out;
    }

    Node find(String path) {
        Node n = root;
        for (String s : segments(path)) {
            n = n.child(s);
            if (n == null) return null;
        }
        return n;
    }

    Node mkdirs(String path) {
        return mkdirs(root, path);
    }

    /** Puts back a file saved in an earlier session (UserDataStore). */
    void restoreFile(String path, byte[] data) {
        int slash = path.lastIndexOf('/');
        Node dir = mkdirs(path.substring(0, slash));
        String name = path.substring(slash + 1);
        Node file = dir.child(name);
        if (file == null || file.directory) {
            file = dir.addChild(new Node(name, false));
        }
        file.data = data;
        file.size = data.length;
        file.remoteUrl = null;
        file.packOffset = -1;
        file.readOnly = false;
    }

    /** Creates a directory and its parents (for folders the game expects to exist). */
    public void ensureDirectory(String path) {
        mkdirs(path);
    }

    private static Node mkdirs(Node from, String path) {
        Node n = from;
        for (String s : segments(path)) {
            Node c = n.child(s);
            if (c == null) c = n.addChild(new Node(s, true));
            n = c;
        }
        return n;
    }

    /** Files and packs from this size up are dropped again once idle, see {@link #trim}. */
    private static final int BIG = 1 << 20;
    private static final int IDLE_MS = 5000;

    /** Downloads a remote file's contents on first use (a whole pack for packed files). */
    void ensureLoaded(Node n) throws IOException {
        if (n.data != null || n.remoteUrl == null) return;
        recordFetch(n.path());
        if (n.packOffset >= 0) {
            byte[] pack = packs.get(n.remoteUrl);
            if (pack == null) {
                pack = fetch(n.remoteUrl);
                packs.put(n.remoteUrl, pack);
            }
            lastBigUse = System.currentTimeMillis();
            scheduleTrim(IDLE_MS);
            n.data = Arrays.copyOfRange(pack, n.packOffset, n.packOffset + n.size);
            if (n.size >= BIG) bigLoaded.add(n);
            return;
        }
        byte[] bytes = fetch(n.remoteUrl);
        n.data = bytes;
        n.size = bytes.length;
        if (n.size >= BIG && n.readOnly) {
            bigLoaded.add(n);
            lastBigUse = System.currentTimeMillis();
            scheduleTrim(IDLE_MS);
        }
    }

    /** Called on every read of a file: a big file dropped by {@link #trim} comes back, and its
     *  idle time starts again. */
    void touch(Node n) throws IOException {
        if (n.data == null) ensureLoaded(n);
        else if (n.size >= BIG && n.remoteUrl != null) lastBigUse = System.currentTimeMillis();
    }

    /**
     * The whole packs and big read-only files (the 27 MB card script zip) are only needed while
     * the game starts. Once nothing has used them for {@link #IDLE_MS}, the packs are forgotten
     * and the big files drop their contents; they are downloaded again if something reads them
     * later (an open file keeps its Node, and {@link #touch} reloads it). Files copied out of a
     * pack keep their own data.
     */
    private void trim() {
        trimScheduled = false;
        long idle = System.currentTimeMillis() - lastBigUse;
        if (idle < IDLE_MS) {
            scheduleTrim(IDLE_MS - idle);
            return;
        }
        trimNow();
    }

    /** Drops the packs and big files now (the idle timer calls this; the self test too). */
    public void trimNow() {
        packs.clear();
        for (Node n : bigLoaded) {
            if (n.remoteUrl != null && n.readOnly) n.data = null;
        }
        bigLoaded.clear();
    }

    private void scheduleTrim(long delayMs) {
        if (trimScheduled) return;
        trimScheduled = true;
        setTimeout(this::trim, (int) delayMs + 50);
    }

    @org.teavm.jso.JSFunctor
    interface Callback extends org.teavm.jso.JSObject {
        void call();
    }

    @org.teavm.jso.JSBody(params = {"callback", "ms"}, script = "setTimeout(callback, ms);")
    private static native void setTimeout(Callback callback, int ms);

    /** Game files read so far, packed or not (window.forgeFetched): scripts/record-startup
     *  turns those of a new game into the startup pack. */
    @org.teavm.jso.JSBody(params = "path", script = "(window.forgeFetched = window.forgeFetched || []).push(path);")
    private static native void recordFetch(String path);

    private byte[] fetch(String url) throws IOException {
        byte[] bytes = Http.getBytes(url);
        remoteFetches++;
        remoteBytes += bytes.length;
        return bytes;
    }

    public int remoteFetches() {
        return remoteFetches;
    }

    public String stats() {
        return remoteFetches + " files / " + (remoteBytes / 1024) + " KB downloaded";
    }

    // --- VirtualFileSystem ---

    @Override
    public String getUserDir() {
        return userDir;
    }

    @Override
    public VirtualFile getFile(String path) {
        // java.io resolves relative paths before calling us; TeaVM's java.nio passes them raw.
        if (!path.startsWith("/")) {
            path = userDir + path;
        }
        return new WebVirtualFile(this, path);
    }

    @Override
    public boolean isWindows() {
        return false;
    }

    @Override
    public String canonicalize(String path) {
        return "/" + String.join("/", segments(path));
    }

    @Override
    public String[] getRoots() {
        return new String[] {"/"};
    }
}
