"""Generate web stand-ins for tinylog's Logger (static) and TaggedLogger (instance).

They print info/warn/error to the browser console and drop debug/trace.
Run from the repo root: python3 web/tools/gen_tinylog_stubs.py
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "main", "java", "forgeweb", "stub", "org", "tinylog")
LEVELS = ["trace", "debug", "info", "warn", "error"]
# (parameter list, arguments passed to emit)
SHAPES = [
    ("Object message", "null, String.valueOf(message), null"),
    ("String message, Object... arguments", "null, message, arguments"),
    ("String message, Supplier<?>... arguments", "null, message, arguments"),
    ("Throwable exception", "exception, null, null"),
    ("Throwable exception, String message", "exception, message, null"),
    ("Throwable exception, String message, Object... arguments", "exception, message, arguments"),
    ("Throwable exception, String message, Supplier<?>... arguments", "exception, message, arguments"),
    ("Throwable exception, Supplier<String> message", "exception, String.valueOf(message.get()), null"),
    ("Supplier<?> message", "null, String.valueOf(message.get()), null"),
]

HELPERS = """
    private static final int MIN_LEVEL = 2; // info

    private static void emit(int level, String tag, Throwable ex, String message, Object[] args) {
        if (level < MIN_LEVEL) return;
        StringBuilder sb = new StringBuilder();
        sb.append(LEVEL_NAMES[level]);
        if (tag != null) sb.append(" [").append(tag).append(']');
        sb.append(' ');
        if (message != null) {
            int argIndex = 0;
            for (int i = 0; i < message.length(); i++) {
                if (args != null && argIndex < args.length && message.startsWith("{}", i)) {
                    Object a = args[argIndex++];
                    if (a instanceof Supplier) a = ((Supplier<?>) a).get();
                    sb.append(a);
                    i++;
                } else {
                    sb.append(message.charAt(i));
                }
            }
        }
        if (ex != null) sb.append(message != null ? ": " : "").append(ex);
        System.out.println(sb);
        if (ex != null && level >= 3) ex.printStackTrace();
    }

    private static final String[] LEVEL_NAMES = {"TRACE", "DEBUG", "INFO", "WARN", "ERROR"};
"""


def methods(static):
    out = []
    mod = "public static" if static else "public"
    tag = "null" if static else "tag"
    for i, lvl in enumerate(LEVELS):
        out.append(f"    {mod} boolean is{lvl.capitalize()}Enabled() {{ return {i} >= MIN_LEVEL; }}")
        for params, args in SHAPES:
            out.append(f"    {mod} void {lvl}({params}) {{ emit({i}, {tag}, {args}); }}")
    return "\n".join(out)


header = """// Generated by web/tools/gen_tinylog_stubs.py; do not edit by hand.
// Substituted for the real class by forgeweb.ForgeWebSubstitutionPolicy.
package forgeweb.stub.org.tinylog;

import org.tinylog.Supplier;
"""

logger = header + """
/** Web stand-in for org.tinylog.Logger (the real one needs threads, reflection and file writers). */
public final class Logger {
    public static TaggedLogger tag(String tag) { return new TaggedLogger(tag); }
    public static TaggedLogger tags(String... tags) { return new TaggedLogger(tags.length > 0 ? tags[0] : null); }

""" + methods(True) + "\n" + HELPERS + "}\n"

tagged = header + """
import java.util.Set;

/** Web stand-in for org.tinylog.TaggedLogger. */
public final class TaggedLogger {
    private final String tag;

    TaggedLogger(String tag) { this.tag = tag; }
    TaggedLogger(Set<String> tags) { this.tag = tags == null || tags.isEmpty() ? null : tags.iterator().next(); }

""" + methods(False) + "\n" + HELPERS + "}\n"

os.makedirs(OUT, exist_ok=True)
with open(os.path.join(OUT, "Logger.java"), "w") as f:
    f.write(logger)
with open(os.path.join(OUT, "TaggedLogger.java"), "w") as f:
    f.write(tagged)
print("wrote", OUT)
