// Generated by web/tools/gen_tinylog_stubs.py; do not edit by hand.
// Substituted for the real class by forgeweb.ForgeWebSubstitutionPolicy.
package forgeweb.stub.org.tinylog;

import org.tinylog.Supplier;

/** Web stand-in for org.tinylog.Logger (the real one needs threads, reflection and file writers). */
public final class Logger {
    public static TaggedLogger tag(String tag) { return new TaggedLogger(tag); }
    public static TaggedLogger tags(String... tags) { return new TaggedLogger(tags.length > 0 ? tags[0] : null); }

    public static boolean isTraceEnabled() { return 0 >= MIN_LEVEL; }
    public static void trace(Object message) { emit(0, null, null, String.valueOf(message), null); }
    public static void trace(String message, Object... arguments) { emit(0, null, null, message, arguments); }
    public static void trace(String message, Supplier<?>... arguments) { emit(0, null, null, message, arguments); }
    public static void trace(Throwable exception) { emit(0, null, exception, null, null); }
    public static void trace(Throwable exception, String message) { emit(0, null, exception, message, null); }
    public static void trace(Throwable exception, String message, Object... arguments) { emit(0, null, exception, message, arguments); }
    public static void trace(Throwable exception, String message, Supplier<?>... arguments) { emit(0, null, exception, message, arguments); }
    public static void trace(Throwable exception, Supplier<String> message) { emit(0, null, exception, String.valueOf(message.get()), null); }
    public static void trace(Supplier<?> message) { emit(0, null, null, String.valueOf(message.get()), null); }
    public static boolean isDebugEnabled() { return 1 >= MIN_LEVEL; }
    public static void debug(Object message) { emit(1, null, null, String.valueOf(message), null); }
    public static void debug(String message, Object... arguments) { emit(1, null, null, message, arguments); }
    public static void debug(String message, Supplier<?>... arguments) { emit(1, null, null, message, arguments); }
    public static void debug(Throwable exception) { emit(1, null, exception, null, null); }
    public static void debug(Throwable exception, String message) { emit(1, null, exception, message, null); }
    public static void debug(Throwable exception, String message, Object... arguments) { emit(1, null, exception, message, arguments); }
    public static void debug(Throwable exception, String message, Supplier<?>... arguments) { emit(1, null, exception, message, arguments); }
    public static void debug(Throwable exception, Supplier<String> message) { emit(1, null, exception, String.valueOf(message.get()), null); }
    public static void debug(Supplier<?> message) { emit(1, null, null, String.valueOf(message.get()), null); }
    public static boolean isInfoEnabled() { return 2 >= MIN_LEVEL; }
    public static void info(Object message) { emit(2, null, null, String.valueOf(message), null); }
    public static void info(String message, Object... arguments) { emit(2, null, null, message, arguments); }
    public static void info(String message, Supplier<?>... arguments) { emit(2, null, null, message, arguments); }
    public static void info(Throwable exception) { emit(2, null, exception, null, null); }
    public static void info(Throwable exception, String message) { emit(2, null, exception, message, null); }
    public static void info(Throwable exception, String message, Object... arguments) { emit(2, null, exception, message, arguments); }
    public static void info(Throwable exception, String message, Supplier<?>... arguments) { emit(2, null, exception, message, arguments); }
    public static void info(Throwable exception, Supplier<String> message) { emit(2, null, exception, String.valueOf(message.get()), null); }
    public static void info(Supplier<?> message) { emit(2, null, null, String.valueOf(message.get()), null); }
    public static boolean isWarnEnabled() { return 3 >= MIN_LEVEL; }
    public static void warn(Object message) { emit(3, null, null, String.valueOf(message), null); }
    public static void warn(String message, Object... arguments) { emit(3, null, null, message, arguments); }
    public static void warn(String message, Supplier<?>... arguments) { emit(3, null, null, message, arguments); }
    public static void warn(Throwable exception) { emit(3, null, exception, null, null); }
    public static void warn(Throwable exception, String message) { emit(3, null, exception, message, null); }
    public static void warn(Throwable exception, String message, Object... arguments) { emit(3, null, exception, message, arguments); }
    public static void warn(Throwable exception, String message, Supplier<?>... arguments) { emit(3, null, exception, message, arguments); }
    public static void warn(Throwable exception, Supplier<String> message) { emit(3, null, exception, String.valueOf(message.get()), null); }
    public static void warn(Supplier<?> message) { emit(3, null, null, String.valueOf(message.get()), null); }
    public static boolean isErrorEnabled() { return 4 >= MIN_LEVEL; }
    public static void error(Object message) { emit(4, null, null, String.valueOf(message), null); }
    public static void error(String message, Object... arguments) { emit(4, null, null, message, arguments); }
    public static void error(String message, Supplier<?>... arguments) { emit(4, null, null, message, arguments); }
    public static void error(Throwable exception) { emit(4, null, exception, null, null); }
    public static void error(Throwable exception, String message) { emit(4, null, exception, message, null); }
    public static void error(Throwable exception, String message, Object... arguments) { emit(4, null, exception, message, arguments); }
    public static void error(Throwable exception, String message, Supplier<?>... arguments) { emit(4, null, exception, message, arguments); }
    public static void error(Throwable exception, Supplier<String> message) { emit(4, null, exception, String.valueOf(message.get()), null); }
    public static void error(Supplier<?> message) { emit(4, null, null, String.valueOf(message.get()), null); }

    private static final int MIN_LEVEL = 2; // info

    private static void emit(int level, String tag, Throwable ex, String message, Object[] args) {
        if (level < MIN_LEVEL) return;
        StringBuilder sb = new StringBuilder();
        sb.append(LEVEL_NAMES[level]);
        if (tag != null) sb.append(" [").append(tag).append(']');
        sb.append(' ');
        if (message != null) {
            int argIndex = 0;
            for (int i = 0; i < message.length(); i++) {
                if (args != null && argIndex < args.length && message.startsWith("{}", i)) {
                    Object a = args[argIndex++];
                    if (a instanceof Supplier) a = ((Supplier<?>) a).get();
                    sb.append(a);
                    i++;
                } else {
                    sb.append(message.charAt(i));
                }
            }
        }
        if (ex != null) sb.append(message != null ? ": " : "").append(ex);
        System.out.println(sb);
        if (ex != null && level >= 3) ex.printStackTrace();
    }

    private static final String[] LEVEL_NAMES = {"TRACE", "DEBUG", "INFO", "WARN", "ERROR"};
}
