// Generated by web/tools/gen_tinylog_stubs.py; do not edit by hand.
// Substituted for the real class by forgeweb.ForgeWebSubstitutionPolicy.
package forgeweb.stub.org.tinylog;

import org.tinylog.Supplier;

import java.util.Set;

/** Web stand-in for org.tinylog.TaggedLogger. */
public final class TaggedLogger {
    private final String tag;

    TaggedLogger(String tag) { this.tag = tag; }
    TaggedLogger(Set<String> tags) { this.tag = tags == null || tags.isEmpty() ? null : tags.iterator().next(); }

    public boolean isTraceEnabled() { return 0 >= MIN_LEVEL; }
    public void trace(Object message) { emit(0, tag, null, String.valueOf(message), null); }
    public void trace(String message, Object... arguments) { emit(0, tag, null, message, arguments); }
    public void trace(String message, Supplier<?>... arguments) { emit(0, tag, null, message, arguments); }
    public void trace(Throwable exception) { emit(0, tag, exception, null, null); }
    public void trace(Throwable exception, String message) { emit(0, tag, exception, message, null); }
    public void trace(Throwable exception, String message, Object... arguments) { emit(0, tag, exception, message, arguments); }
    public void trace(Throwable exception, String message, Supplier<?>... arguments) { emit(0, tag, exception, message, arguments); }
    public void trace(Throwable exception, Supplier<String> message) { emit(0, tag, exception, String.valueOf(message.get()), null); }
    public void trace(Supplier<?> message) { emit(0, tag, null, String.valueOf(message.get()), null); }
    public boolean isDebugEnabled() { return 1 >= MIN_LEVEL; }
    public void debug(Object message) { emit(1, tag, null, String.valueOf(message), null); }
    public void debug(String message, Object... arguments) { emit(1, tag, null, message, arguments); }
    public void debug(String message, Supplier<?>... arguments) { emit(1, tag, null, message, arguments); }
    public void debug(Throwable exception) { emit(1, tag, exception, null, null); }
    public void debug(Throwable exception, String message) { emit(1, tag, exception, message, null); }
    public void debug(Throwable exception, String message, Object... arguments) { emit(1, tag, exception, message, arguments); }
    public void debug(Throwable exception, String message, Supplier<?>... arguments) { emit(1, tag, exception, message, arguments); }
    public void debug(Throwable exception, Supplier<String> message) { emit(1, tag, exception, String.valueOf(message.get()), null); }
    public void debug(Supplier<?> message) { emit(1, tag, null, String.valueOf(message.get()), null); }
    public boolean isInfoEnabled() { return 2 >= MIN_LEVEL; }
    public void info(Object message) { emit(2, tag, null, String.valueOf(message), null); }
    public void info(String message, Object... arguments) { emit(2, tag, null, message, arguments); }
    public void info(String message, Supplier<?>... arguments) { emit(2, tag, null, message, arguments); }
    public void info(Throwable exception) { emit(2, tag, exception, null, null); }
    public void info(Throwable exception, String message) { emit(2, tag, exception, message, null); }
    public void info(Throwable exception, String message, Object... arguments) { emit(2, tag, exception, message, arguments); }
    public void info(Throwable exception, String message, Supplier<?>... arguments) { emit(2, tag, exception, message, arguments); }
    public void info(Throwable exception, Supplier<String> message) { emit(2, tag, exception, String.valueOf(message.get()), null); }
    public void info(Supplier<?> message) { emit(2, tag, null, String.valueOf(message.get()), null); }
    public boolean isWarnEnabled() { return 3 >= MIN_LEVEL; }
    public void warn(Object message) { emit(3, tag, null, String.valueOf(message), null); }
    public void warn(String message, Object... arguments) { emit(3, tag, null, message, arguments); }
    public void warn(String message, Supplier<?>... arguments) { emit(3, tag, null, message, arguments); }
    public void warn(Throwable exception) { emit(3, tag, exception, null, null); }
    public void warn(Throwable exception, String message) { emit(3, tag, exception, message, null); }
    public void warn(Throwable exception, String message, Object... arguments) { emit(3, tag, exception, message, arguments); }
    public void warn(Throwable exception, String message, Supplier<?>... arguments) { emit(3, tag, exception, message, arguments); }
    public void warn(Throwable exception, Supplier<String> message) { emit(3, tag, exception, String.valueOf(message.get()), null); }
    public void warn(Supplier<?> message) { emit(3, tag, null, String.valueOf(message.get()), null); }
    public boolean isErrorEnabled() { return 4 >= MIN_LEVEL; }
    public void error(Object message) { emit(4, tag, null, String.valueOf(message), null); }
    public void error(String message, Object... arguments) { emit(4, tag, null, message, arguments); }
    public void error(String message, Supplier<?>... arguments) { emit(4, tag, null, message, arguments); }
    public void error(Throwable exception) { emit(4, tag, exception, null, null); }
    public void error(Throwable exception, String message) { emit(4, tag, exception, message, null); }
    public void error(Throwable exception, String message, Object... arguments) { emit(4, tag, exception, message, arguments); }
    public void error(Throwable exception, String message, Supplier<?>... arguments) { emit(4, tag, exception, message, arguments); }
    public void error(Throwable exception, Supplier<String> message) { emit(4, tag, exception, String.valueOf(message.get()), null); }
    public void error(Supplier<?> message) { emit(4, tag, null, String.valueOf(message.get()), null); }

    private static final int MIN_LEVEL = 2; // info

    private static void emit(int level, String tag, Throwable ex, String message, Object[] args) {
        if (level < MIN_LEVEL) return;
        StringBuilder sb = new StringBuilder();
        sb.append(LEVEL_NAMES[level]);
        if (tag != null) sb.append(" [").append(tag).append(']');
        sb.append(' ');
        if (message != null) {
            int argIndex = 0;
            for (int i = 0; i < message.length(); i++) {
                if (args != null && argIndex < args.length && message.startsWith("{}", i)) {
                    Object a = args[argIndex++];
                    if (a instanceof Supplier) a = ((Supplier<?>) a).get();
                    sb.append(a);
                    i++;
                } else {
                    sb.append(message.charAt(i));
                }
            }
        }
        if (ex != null) sb.append(message != null ? ": " : "").append(ex);
        System.out.println(sb);
        if (ex != null && level >= 3) ex.printStackTrace();
    }

    private static final String[] LEVEL_NAMES = {"TRACE", "DEBUG", "INFO", "WARN", "ERROR"};
}
